app = 'datum-server'
primary_region = 'cdg'

[build]
  image = 'ghcr.io/a-saed/datum-server'

[env]
  TABLE = "features"
  ALLOWED_ORIGIN = "https://a-saed.github.io"
  RATE_LIMIT = "5"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
